function createNode(id, x, y) {
  return {
    id,
    label: id,
    x,
    y,
  };
}

export const levels = [
  {
    id: 1,
    name: "Connected Graph",
    concept: "Connected Graph",
    instruction: "Hubungkan semua komputer agar setiap node dapat dicapai.",
    nodes: [
      createNode("A", 22, 35),
      createNode("B", 52, 24),
      createNode("C", 78, 44),
      createNode("D", 44, 72),
    ],
    goals: [{ type: "CONNECT_ALL" }],
  },
  {
    id: 2,
    name: "Minimum Connection",
    concept: "Minimum Connection",
    instruction: "Hubungkan semua komputer dengan tepat 3 kabel.",
    nodes: [
      createNode("A", 18, 26),
      createNode("B", 50, 24),
      createNode("C", 79, 34),
      createNode("D", 39, 73),
    ],
    goals: [{ type: "SPANNING_TREE" }],
  },
  {
    id: 3,
    name: "Path",
    concept: "Path",
    instruction: "Buat jalur dari A ke D. Kamu boleh memakai node perantara.",
    nodes: [
      createNode("A", 16, 50),
      createNode("B", 39, 28),
      createNode("C", 61, 70),
      createNode("D", 84, 50),
    ],
    availableEdges: [
      { from: "A", to: "B" },
      { from: "B", to: "C" },
      { from: "C", to: "D" },
      { from: "A", to: "C" },
    ],
    goals: [{ type: "SHORTEST_PATH", startNode: "A", endNode: "D" }],
  },
  {
    id: 4,
    name: "No Cycle",
    concept: "No Cycle",
    instruction: "Hubungkan semua komputer tanpa membuat cycle.",
    nodes: [
      createNode("A", 20, 23),
      createNode("B", 50, 18),
      createNode("C", 78, 32),
      createNode("D", 70, 75),
      createNode("E", 29, 73),
    ],
    goals: [{ type: "NO_CYCLE", requireConnected: true }],
  },
  {
    id: 5,
    name: "Weighted Graph",
    concept: "Weighted Graph",
    instruction: "Pilih jalur A ke D dengan biaya terkecil. Angka pada kabel adalah biaya.",
    nodes: [
      createNode("A", 18, 51),
      createNode("B", 43, 28),
      createNode("C", 43, 74),
      createNode("D", 78, 51),
    ],
    availableEdges: [
      { from: "A", to: "B", weight: 2 },
      { from: "B", to: "D", weight: 2 },
      { from: "A", to: "C", weight: 5 },
      { from: "C", to: "D", weight: 5 },
      { from: "B", to: "C", weight: 4 },
    ],
    goals: [
      {
        type: "SHORTEST_PATH",
        startNode: "A",
        endNode: "D",
        maxDistance: 4,
        exactPath: ["A", "B", "D"],
        exactEdgeCount: 2,
      },
    ],
  },
  {
    id: 6,
    name: "Spanning Tree",
    concept: "Spanning Tree",
    instruction: "Buat spanning tree: semua node terhubung, tanpa cycle, dengan kabel minimum.",
    nodes: [
      createNode("A", 18, 24),
      createNode("B", 51, 20),
      createNode("C", 82, 32),
      createNode("D", 72, 75),
      createNode("E", 34, 78),
      createNode("F", 16, 54),
    ],
    goals: [{ type: "SPANNING_TREE" }],
  },
  {
    id: 7,
    name: "Degree",
    concept: "Degree",
    instruction: "Buat node C memiliki degree 3.",
    nodes: [
      createNode("A", 18, 24),
      createNode("B", 50, 18),
      createNode("C", 50, 52),
      createNode("D", 82, 24),
      createNode("E", 50, 82),
    ],
    goals: [{ type: "DEGREE", targetNode: "C", targetDegree: 3 }],
  },
  {
    id: 8,
    name: "Disconnected Graph",
    concept: "Disconnected Graph",
    instruction: "Jaringan masih terputus. Tambahkan kabel agar semua komputer tersambung.",
    nodes: [
      createNode("A", 20, 27),
      createNode("B", 39, 50),
      createNode("C", 20, 74),
      createNode("D", 72, 29),
      createNode("E", 83, 63),
      createNode("F", 63, 78),
    ],
    initialEdges: [
      { from: "A", to: "B" },
      { from: "B", to: "C" },
      { from: "D", to: "E" },
      { from: "E", to: "F" },
    ],
    goals: [{ type: "CONNECT_ALL" }],
  },
  {
    id: 9,
    name: "Shortest Path",
    concept: "Shortest Path",
    instruction: "Cari jalur terpendek dari A ke F berdasarkan biaya kabel.",
    nodes: [
      createNode("A", 12, 50),
      createNode("B", 31, 24),
      createNode("C", 31, 76),
      createNode("D", 56, 24),
      createNode("E", 56, 76),
      createNode("F", 84, 50),
    ],
    availableEdges: [
      { from: "A", to: "B", weight: 1 },
      { from: "B", to: "D", weight: 2 },
      { from: "D", to: "F", weight: 2 },
      { from: "A", to: "C", weight: 3 },
      { from: "C", to: "E", weight: 3 },
      { from: "E", to: "F", weight: 1 },
      { from: "B", to: "E", weight: 5 },
      { from: "C", to: "D", weight: 4 },
    ],
    goals: [
      {
        type: "SHORTEST_PATH",
        startNode: "A",
        endNode: "F",
        maxDistance: 5,
        exactPath: ["A", "B", "D", "F"],
        exactEdgeCount: 3,
      },
    ],
  },
  {
    id: 10,
    name: "Final Challenge",
    concept: "Final Challenge",
    instruction: "Buat jaringan akhir yang connected, tanpa cycle, dan merupakan spanning tree.",
    nodes: [
      createNode("A", 17, 28),
      createNode("B", 42, 17),
      createNode("C", 69, 22),
      createNode("D", 84, 52),
      createNode("E", 62, 82),
      createNode("F", 30, 80),
      createNode("G", 13, 55),
    ],
    goals: [
      { type: "CONNECT_ALL" },
      { type: "NO_CYCLE" },
      { type: "SPANNING_TREE" },
    ],
  },
];
